### ISSUE TITLE
Checklist for v1.0.0

### ISSUE THREAD

**Issue by shoghicp** [PocketMine/RakLib#1]
- [x] Add force-send to main thread frontend
- [x] Add correct ACK notification to main thread
- [ ] Add variable MTU
- [x] Kick on too long recovery queue
- [x] Change server name (or property) from main thread
- [x] Add Query / Unknown packet support

**Comment by Subtleoliver** [comment]
So. Shogi. Why isn't this done? After over 2 years.
